-- 코드를 입력하세요
SELECT A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(A.PRICE * C.SALES) AS SALES
FROM BOOK_SALES C
JOIN BOOK A ON C.BOOK_ID = A.BOOK_id
JOIN AUTHOR B ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE C.SALES_DATE LIKE '2022-01%'
GROUP BY 2,3
ORDER BY 1,3 DESC