-- 코드를 입력하세요
WITH DISCOUNT AS (
    SELECT CAR_TYPE, 1-(DISCOUNT_RATE*0.01) AS RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = '30일 이상'
)

SELECT A.CAR_ID,
        A.CAR_TYPE,
        ROUND(A.DAILY_FEE * 30 * RATE,0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A
JOIN DISCOUNT C ON A.CAR_TYPE = C.CAR_TYPE
WHERE A.CAR_TYPE IN ('세단','SUV')
    AND ROUND(30*A.DAILY_FEE*RATE) >= 500000
    AND ROUND(30*A.DAILY_FEE*RATE) < 2000000
    AND CAR_ID NOT IN (SELECT DISTINCT CAR_ID
                        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                        WHERE END_DATE >= '2022-11-01'
                      )
ORDER BY 3 DESC, 2, 1 DESC