-- 코드를 입력하세요
SELECT FOOD_TYPE,REST_ID,REST_NAME,FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE,FAVORITES) IN
    (select FOOD_TYPE,MAX(FAVORITES)
     from REST_INFO
     group by FOOD_TYPE
     )
ORDER BY FOOD_TYPE DESC