-- 코드를 입력하세요
WITH 2021_JOINED AS (
    SELECT *
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)

SELECT YEAR(B.SALES_DATE) AS YEAR,
    MONTH(B.SALES_DATE) AS MONTH,
    COUNT(DISTINCT B.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT B.USER_ID) / (SELECT COUNT(*) FROM 2021_JOINED),1) AS PURCHASED_RATIO
FROM ONLINE_SALE B
JOIN 2021_JOINED C ON B.USER_ID = C.USER_ID
WHERE B.USER_ID IN (SELECT USER_ID FROM 2021_JOINED)
GROUP BY 1,2
ORDER BY 1,2