-- 코드를 입력하세요
WITH RECURSIVE HOURS AS (
    SELECT 0 AS hour
    UNION ALL
    SELECT hour + 1
    FROM HOURS
    WHERE HOUR < 23
)

SELECT A.hour AS HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM HOURS A
LEFT JOIN ANIMAL_OUTS B ON A.hour = HOUR(B.DATETIME)
GROUP BY HOUR
ORDER BY HOUR