-- 코드를 입력하세요
WITH MAX_NUM AS (
    select MEMBER_ID
    from REST_REVIEW
    group by MEMBER_ID
    order by COUNT(*) DESC
    limit 1)

SELECT A.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE A
JOIN REST_REVIEW B ON A.MEMBER_ID = B.MEMBER_ID
WHERE A.MEMBER_ID = (SELECT MEMBER_ID FROM MAX_NUM)
ORDER BY 3,2
