-- 코드를 작성해주세요
SELECT A.ID,B.FISH_NAME,A.LENGTH
FROM FISH_INFO A
JOIN FISH_NAME_INFO B ON A.FISH_TYPE = B.FISH_TYPE
WHERE A.LENGTH IN (
    select MAX(LENGTH)
    from FISH_INFO
    where FISH_TYPE = A.FISH_TYPE
    group by FISH_TYPE
)
ORDER BY A.ID 